<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>Hermes.TradingPlatform.Wpf</RootNamespace>
    <ApplicationIcon />
    <AssemblyName>Hermes.TradingPlatform</AssemblyName>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hermes.TradingPlatform.Shared\Hermes.TradingPlatform.Shared.csproj" />
    <ProjectReference Include="..\Hermes.TradingPlatform.Core\Hermes.TradingPlatform.Core.csproj" />
  </ItemGroup>
</Project>
