<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Hermes.SpotTerminal.Cli</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hermes.SpotTerminal.Shared\Hermes.SpotTerminal.Shared.csproj" />
    <ProjectReference Include="..\..\Hermes.Terminals.Shared\Hermes.Terminals.Shared.csproj" />
  </ItemGroup>
</Project>
